### ISSUE TITLE
Website has viewing issues on smaller screens (Mobile)

### ISSUE THREAD

**Issue by SizableShrimp** [ParchmentMC/Website#13]
When content is indented too much, it leads to this hard to read mess:
![Demo of bad viewing experience on small viewport](https://user-images.githubusercontent.com/29855886/200181596-38aab82f-8388-4832-8d1a-b1ab7ce2df17.png)

**Comment by T3sT3ro** [comment]
H1 on the main page doesn't fit as well. Try scaling it to max width
